BitBucketWeb/Controllers/IssueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BitBucketService;

namespace BitBucketWeb.Controllers
{
    public class IssueController : Controller
    {

        private readonly RepositoryIssues _issuesRepository;

        public IssueController()
        {
            _issuesRepository = new RepositoryIssues();
        }

        // GET: Issue
        public ActionResult Create(string accountName, string slug)
        {
            ViewBag.AccountName = accountName;
            ViewBag.Slug = slug;
            return View();
        }

        [HttpPost]
        public ActionResult Create(RepositoryIssues newIssue, string accountName, string slug)
        {
            try
            {
                _issuesRepository.Save(newIssue, accountName, slug);
                return RedirectToAction("Activity", "Home", new { accountName = accountName, slug = slug });
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(string accountName, string slug, int issueId)
        {
            ViewBag.AccountName = accountName;
            ViewBag.Slug = slug;

            var issue = _issuesRepository.GetById(accountName, slug, issueId);
            return View(issue);
        }

        [HttpPost]
        public ActionResult Edit(RepositoryIssues updatedIssue, string accountName, string slug)
        {
            try
            {
                _issuesRepository.Update(updatedIssue, accountName, slug);
                return RedirectToAction("Activity", "Home", new { accountName = accountName, slug = slug });
            }
            catch
            {
                return View();
            }
        }
    }
}

BitBucketWeb/Views/Issue/Create.cshtml
@model BitBucketService.RepositoryIssues

@{
    ViewBag.Title = "Create";
}

<h2>Create New Issue</h2>
@using (Html.BeginForm("Create", "Issue", new { accountName = ViewBag.AccountName, slug = ViewBag.Slug }, FormMethod.Post, new { @class = "form-horizontal" }))
{

    <div class="form-group">
        @Html.LabelFor(model => model.Title, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Content, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextAreaFor(model => model.Content, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Kind, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            <select name="Kind" class="form-control">
                <option>bug</option>
                <option>enhancement</option>
                <option>proposal</option>
                <option>task</option>
            </select>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Priority, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            <select name="Priority" class="form-control">
                <option>trivial</option>
                <option>minor</option>
                <option>major</option>
                <option>critical</option>
                <option>blocker</option>
            </select>
        </div>
    </div>
    <div class="form-group">
        <input class="btn btn-primary col-md-offset-2" type="submit" value="Create Issue" />
    </div>
}

BitBucketWeb/Views/Issue/Edit.cshtml
@model BitBucketService.RepositoryIssues
@{
    ViewBag.Title = "Edit";
}

<h2>Edit an Issue</h2>

@using (Html.BeginForm("Edit", "Issue", new { accountName = ViewBag.AccountName, slug = ViewBag.Slug }, FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.Kind)
    @Html.HiddenFor(model => model.Priority)
    
    <div class="form-group">
        @Html.LabelFor(model => model.Title, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Content, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextAreaFor(model => model.Content, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Kind, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            <select name="Kind" class="form-control">
                <option value="bug">bug</option>
                <option value="enhancement">enhancement</option>
                <option value="proposal">proposal</option>
                <option value="task">task</option>
            </select>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Priority, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            <select name="Priority" class="form-control">
                <option value="trivial">trivial</option>
                <option value="minor">minor</option>
                <option value="major">major</option>
                <option value="critical">critical</option>
                <option value="blocker">blocker</option>
            </select>
        </div>
    </div>
    <div>
        <input class="btn btn-primary col-md-offset-2" type="submit" value="Update an Issue" />
    </div>
}

@section scripts
{
    <script src="~/Scripts/issues-edit.js"></script>
}